executa: main.c
	gcc main.c -o HollowPriest.out game.c menu.c list.c colision.c -lallegro -lallegro_ttf -lallegro_font -lallegro_image -lallegro_audio -lallegro_acodec -lallegro_primitives -Wall
	./HollowPriest.out